http {
    # Include the mime types file so we can serve files correctly
    include /etc/nginx/mime.types;
    
    server {
        # For now, we only worry about HTTP
        listen 80;
        # No DNS, so we use localhost
        server_name localhost;
        # Point to the root of the static files
        root /usr/share/nginx/html;
        # Default page
        index index.html;

        location / {
            # Don't need anything in here because of the root directive above
        }
    }
}

# This has to be defined otherwise nginx will not start
events {}