// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(PostgresDbContext))]
    [Migration("20250211010123_TestStudentDataSeeding")]
    partial class TestStudentDataSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Entities.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Classification")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Student");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bf9d0fb1-7210-4b75-9dcf-45ab1608a331"),
                            Classification = 0,
                            Name = "Alice"
                        },
                        new
                        {
                            Id = new Guid("79f2b705-43b0-4de3-b92c-5e630acdb059"),
                            Classification = 1,
                            Name = "Bob"
                        },
                        new
                        {
                            Id = new Guid("f2daf9d2-e89d-40f1-be40-100ae86a0c3f"),
                            Classification = 2,
                            Name = "Charlie"
                        },
                        new
                        {
                            Id = new Guid("5b477117-c502-45f5-b167-7d9be43c8a9a"),
                            Classification = 3,
                            Name = "David"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
